### ISSUE TITLE
Wrong show address via u2f-api

### ISSUE THREAD

**Issue by lich666dead** [CryptoAeon/zil-ledger-nano-s#9]
### Hello, when make requests to "getPublicAddress", Ledger show address wrong length.

* requests from hw-transport-u2f:
![photo_2019-06-16_07-53-01](https://user-images.githubusercontent.com/21293723/59561927-4c47d600-9015-11e9-91f3-ef6157d0f3b8.jpg)

* request from hw-transport-node-hid:
![photo_2019-06-16_07-53-29](https://user-images.githubusercontent.com/21293723/59561938-6386c380-9015-11e9-8c0b-6d23c3e96ca2.jpg)

**Comment by lich666dead** [comment]
it is decided [hero](https://github.com/LedgerHQ/ledgerjs/releases/tag/v4.66.0)

**Comment by hicaru** [comment]
fixed in this [release](https://github.com/CryptoAeon/zil-ledger-nano-s/releases/tag/v0.3.3)

**Comment by vaivaswatha** [comment]
Fixed by https://github.com/CryptoAeon/zil-ledger-nano-s/commit/b0681a390a1f980dd07b9b25cc39ff056f552391
